services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER: root
      - POSTGRES_PASSWORD: 158818
